# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/landing_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobufs.profile_service_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/landing_service.proto',
  package='main.landing_service',
  serialized_pb=_b('\n\x1fprotobufs/landing_service.proto\x12\x14main.landing_service\x1a\x1fprotobufs/profile_service.proto\"\xca\x02\n\x0eLandingService\x1a\x8d\x01\n\nContainers\x1a\x7f\n\x0fProfileCategory\x12\r\n\x05title\x18\x01 \x01(\t\x12H\n\x07\x63ontent\x18\x02 \x03(\x0b\x32\x37.main.profile_service.ProfileService.Containers.Profile\x12\x13\n\x0b\x63ontent_key\x18\x03 \x01(\t\x1a\xa7\x01\n\rGetCategories\x1a-\n\x07Request\x12\x14\n\nprofile_id\x18\x01 \x01(\tH\x00\x42\x0c\n\nlookup_key\x1ag\n\x08Response\x12[\n\x12profile_categories\x18\x01 \x03(\x0b\x32?.main.landing_service.LandingService.Containers.ProfileCategory')
  ,
  dependencies=[protobufs.profile_service_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LANDINGSERVICE_CONTAINERS_PROFILECATEGORY = _descriptor.Descriptor(
  name='ProfileCategory',
  full_name='main.landing_service.LandingService.Containers.ProfileCategory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='main.landing_service.LandingService.Containers.ProfileCategory.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='main.landing_service.LandingService.Containers.ProfileCategory.content', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content_key', full_name='main.landing_service.LandingService.Containers.ProfileCategory.content_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=251,
)

_LANDINGSERVICE_CONTAINERS = _descriptor.Descriptor(
  name='Containers',
  full_name='main.landing_service.LandingService.Containers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_LANDINGSERVICE_CONTAINERS_PROFILECATEGORY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=251,
)

_LANDINGSERVICE_GETCATEGORIES_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='main.landing_service.LandingService.GetCategories.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_id', full_name='main.landing_service.LandingService.GetCategories.Request.profile_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='lookup_key', full_name='main.landing_service.LandingService.GetCategories.Request.lookup_key',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=271,
  serialized_end=316,
)

_LANDINGSERVICE_GETCATEGORIES_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='main.landing_service.LandingService.GetCategories.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_categories', full_name='main.landing_service.LandingService.GetCategories.Response.profile_categories', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=421,
)

_LANDINGSERVICE_GETCATEGORIES = _descriptor.Descriptor(
  name='GetCategories',
  full_name='main.landing_service.LandingService.GetCategories',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_LANDINGSERVICE_GETCATEGORIES_REQUEST, _LANDINGSERVICE_GETCATEGORIES_RESPONSE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=421,
)

_LANDINGSERVICE = _descriptor.Descriptor(
  name='LandingService',
  full_name='main.landing_service.LandingService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_LANDINGSERVICE_CONTAINERS, _LANDINGSERVICE_GETCATEGORIES, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=421,
)

_LANDINGSERVICE_CONTAINERS_PROFILECATEGORY.fields_by_name['content'].message_type = protobufs.profile_service_pb2._PROFILESERVICE_CONTAINERS_PROFILE
_LANDINGSERVICE_CONTAINERS_PROFILECATEGORY.containing_type = _LANDINGSERVICE_CONTAINERS
_LANDINGSERVICE_CONTAINERS.containing_type = _LANDINGSERVICE
_LANDINGSERVICE_GETCATEGORIES_REQUEST.containing_type = _LANDINGSERVICE_GETCATEGORIES
_LANDINGSERVICE_GETCATEGORIES_REQUEST.oneofs_by_name['lookup_key'].fields.append(
  _LANDINGSERVICE_GETCATEGORIES_REQUEST.fields_by_name['profile_id'])
_LANDINGSERVICE_GETCATEGORIES_REQUEST.fields_by_name['profile_id'].containing_oneof = _LANDINGSERVICE_GETCATEGORIES_REQUEST.oneofs_by_name['lookup_key']
_LANDINGSERVICE_GETCATEGORIES_RESPONSE.fields_by_name['profile_categories'].message_type = _LANDINGSERVICE_CONTAINERS_PROFILECATEGORY
_LANDINGSERVICE_GETCATEGORIES_RESPONSE.containing_type = _LANDINGSERVICE_GETCATEGORIES
_LANDINGSERVICE_GETCATEGORIES.containing_type = _LANDINGSERVICE
DESCRIPTOR.message_types_by_name['LandingService'] = _LANDINGSERVICE

LandingService = _reflection.GeneratedProtocolMessageType('LandingService', (_message.Message,), dict(

  Containers = _reflection.GeneratedProtocolMessageType('Containers', (_message.Message,), dict(

    ProfileCategory = _reflection.GeneratedProtocolMessageType('ProfileCategory', (_message.Message,), dict(
      DESCRIPTOR = _LANDINGSERVICE_CONTAINERS_PROFILECATEGORY,
      __module__ = 'protobufs.landing_service_pb2'
      # @@protoc_insertion_point(class_scope:main.landing_service.LandingService.Containers.ProfileCategory)
      ))
    ,
    DESCRIPTOR = _LANDINGSERVICE_CONTAINERS,
    __module__ = 'protobufs.landing_service_pb2'
    # @@protoc_insertion_point(class_scope:main.landing_service.LandingService.Containers)
    ))
  ,

  GetCategories = _reflection.GeneratedProtocolMessageType('GetCategories', (_message.Message,), dict(

    Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
      DESCRIPTOR = _LANDINGSERVICE_GETCATEGORIES_REQUEST,
      __module__ = 'protobufs.landing_service_pb2'
      # @@protoc_insertion_point(class_scope:main.landing_service.LandingService.GetCategories.Request)
      ))
    ,

    Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
      DESCRIPTOR = _LANDINGSERVICE_GETCATEGORIES_RESPONSE,
      __module__ = 'protobufs.landing_service_pb2'
      # @@protoc_insertion_point(class_scope:main.landing_service.LandingService.GetCategories.Response)
      ))
    ,
    DESCRIPTOR = _LANDINGSERVICE_GETCATEGORIES,
    __module__ = 'protobufs.landing_service_pb2'
    # @@protoc_insertion_point(class_scope:main.landing_service.LandingService.GetCategories)
    ))
  ,
  DESCRIPTOR = _LANDINGSERVICE,
  __module__ = 'protobufs.landing_service_pb2'
  # @@protoc_insertion_point(class_scope:main.landing_service.LandingService)
  ))
_sym_db.RegisterMessage(LandingService)
_sym_db.RegisterMessage(LandingService.Containers)
_sym_db.RegisterMessage(LandingService.Containers.ProfileCategory)
_sym_db.RegisterMessage(LandingService.GetCategories)
_sym_db.RegisterMessage(LandingService.GetCategories.Request)
_sym_db.RegisterMessage(LandingService.GetCategories.Response)


# @@protoc_insertion_point(module_scope)
