# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/organization_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/organization_service.proto',
  package='main.organization_service',
  serialized_pb=_b('\n$protobufs/organization_service.proto\x12\x19main.organization_service\"\x9f\x07\n\x13OrganizationService\x1a\xa1\x01\n\nContainers\x1a\x38\n\x0cOrganization\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x64omain\x18\x03 \x01(\t\x1aY\n\x04Team\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08owner_id\x18\x03 \x01(\t\x12\x17\n\x0forganization_id\x18\x04 \x01(\t\x12\x0c\n\x04path\x18\x05 \x03(\t\x1a\xa7\x01\n\x12\x43reateOrganization\x1a\'\n\x07Request\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x1ah\n\x08Response\x12\\\n\x0corganization\x18\x01 \x01(\x0b\x32\x46.main.organization_service.OrganizationService.Containers.Organization\x1a\xbc\x01\n\nCreateTeam\x1aT\n\x07Request\x12\x17\n\x0forganization_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08owner_id\x18\x03 \x01(\t\x12\x10\n\x08\x63hild_of\x18\x05 \x01(\t\x1aX\n\x08Response\x12L\n\x04team\x18\x01 \x01(\x0b\x32>.main.organization_service.OrganizationService.Containers.Team\x1aH\n\rAddTeamMember\x1a+\n\x07Request\x12\x0f\n\x07team_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x1a\n\n\x08Response\x1aK\n\x10RemoveTeamMember\x1a+\n\x07Request\x12\x0f\n\x07team_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x1a\n\n\x08Response\x1aI\n\x0eGetTeamMembers\x1a\x1a\n\x07Request\x12\x0f\n\x07team_id\x18\x01 \x01(\t\x1a\x1b\n\x08Response\x12\x0f\n\x07members\x18\x01 \x03(\t\x1aJ\n\x0e\x41\x64\x64TeamMembers\x1a,\n\x07Request\x12\x0f\n\x07team_id\x18\x01 \x01(\t\x12\x10\n\x08user_ids\x18\x02 \x03(\t\x1a\n\n\x08Response\x1aM\n\x11RemoveTeamMembers\x1a,\n\x07Request\x12\x0f\n\x07team_id\x18\x01 \x01(\t\x12\x10\n\x08user_ids\x18\x02 \x03(\t\x1a\n\n\x08Response')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ORGANIZATIONSERVICE_CONTAINERS_ORGANIZATION = _descriptor.Descriptor(
  name='Organization',
  full_name='main.organization_service.OrganizationService.Containers.Organization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='main.organization_service.OrganizationService.Containers.Organization.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='main.organization_service.OrganizationService.Containers.Organization.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domain', full_name='main.organization_service.OrganizationService.Containers.Organization.domain', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=162,
)

_ORGANIZATIONSERVICE_CONTAINERS_TEAM = _descriptor.Descriptor(
  name='Team',
  full_name='main.organization_service.OrganizationService.Containers.Team',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='main.organization_service.OrganizationService.Containers.Team.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='main.organization_service.OrganizationService.Containers.Team.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner_id', full_name='main.organization_service.OrganizationService.Containers.Team.owner_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='organization_id', full_name='main.organization_service.OrganizationService.Containers.Team.organization_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='main.organization_service.OrganizationService.Containers.Team.path', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=253,
)

_ORGANIZATIONSERVICE_CONTAINERS = _descriptor.Descriptor(
  name='Containers',
  full_name='main.organization_service.OrganizationService.Containers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ORGANIZATIONSERVICE_CONTAINERS_ORGANIZATION, _ORGANIZATIONSERVICE_CONTAINERS_TEAM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=253,
)

_ORGANIZATIONSERVICE_CREATEORGANIZATION_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='main.organization_service.OrganizationService.CreateOrganization.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='main.organization_service.OrganizationService.CreateOrganization.Request.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='main.organization_service.OrganizationService.CreateOrganization.Request.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=317,
)

_ORGANIZATIONSERVICE_CREATEORGANIZATION_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='main.organization_service.OrganizationService.CreateOrganization.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='organization', full_name='main.organization_service.OrganizationService.CreateOrganization.Response.organization', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=423,
)

_ORGANIZATIONSERVICE_CREATEORGANIZATION = _descriptor.Descriptor(
  name='CreateOrganization',
  full_name='main.organization_service.OrganizationService.CreateOrganization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ORGANIZATIONSERVICE_CREATEORGANIZATION_REQUEST, _ORGANIZATIONSERVICE_CREATEORGANIZATION_RESPONSE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=423,
)

_ORGANIZATIONSERVICE_CREATETEAM_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='main.organization_service.OrganizationService.CreateTeam.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='organization_id', full_name='main.organization_service.OrganizationService.CreateTeam.Request.organization_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='main.organization_service.OrganizationService.CreateTeam.Request.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner_id', full_name='main.organization_service.OrganizationService.CreateTeam.Request.owner_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='child_of', full_name='main.organization_service.OrganizationService.CreateTeam.Request.child_of', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=524,
)

_ORGANIZATIONSERVICE_CREATETEAM_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='main.organization_service.OrganizationService.CreateTeam.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team', full_name='main.organization_service.OrganizationService.CreateTeam.Response.team', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=614,
)

_ORGANIZATIONSERVICE_CREATETEAM = _descriptor.Descriptor(
  name='CreateTeam',
  full_name='main.organization_service.OrganizationService.CreateTeam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ORGANIZATIONSERVICE_CREATETEAM_REQUEST, _ORGANIZATIONSERVICE_CREATETEAM_RESPONSE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=614,
)

_ORGANIZATIONSERVICE_ADDTEAMMEMBER_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='main.organization_service.OrganizationService.AddTeamMember.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_id', full_name='main.organization_service.OrganizationService.AddTeamMember.Request.team_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='main.organization_service.OrganizationService.AddTeamMember.Request.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=633,
  serialized_end=676,
)

_ORGANIZATIONSERVICE_ADDTEAMMEMBER_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='main.organization_service.OrganizationService.AddTeamMember.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=329,
)

_ORGANIZATIONSERVICE_ADDTEAMMEMBER = _descriptor.Descriptor(
  name='AddTeamMember',
  full_name='main.organization_service.OrganizationService.AddTeamMember',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ORGANIZATIONSERVICE_ADDTEAMMEMBER_REQUEST, _ORGANIZATIONSERVICE_ADDTEAMMEMBER_RESPONSE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=616,
  serialized_end=688,
)

_ORGANIZATIONSERVICE_REMOVETEAMMEMBER_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='main.organization_service.OrganizationService.RemoveTeamMember.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_id', full_name='main.organization_service.OrganizationService.RemoveTeamMember.Request.team_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='main.organization_service.OrganizationService.RemoveTeamMember.Request.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=633,
  serialized_end=676,
)

_ORGANIZATIONSERVICE_REMOVETEAMMEMBER_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='main.organization_service.OrganizationService.RemoveTeamMember.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=329,
)

_ORGANIZATIONSERVICE_REMOVETEAMMEMBER = _descriptor.Descriptor(
  name='RemoveTeamMember',
  full_name='main.organization_service.OrganizationService.RemoveTeamMember',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ORGANIZATIONSERVICE_REMOVETEAMMEMBER_REQUEST, _ORGANIZATIONSERVICE_REMOVETEAMMEMBER_RESPONSE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=690,
  serialized_end=765,
)

_ORGANIZATIONSERVICE_GETTEAMMEMBERS_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='main.organization_service.OrganizationService.GetTeamMembers.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_id', full_name='main.organization_service.OrganizationService.GetTeamMembers.Request.team_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=633,
  serialized_end=659,
)

_ORGANIZATIONSERVICE_GETTEAMMEMBERS_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='main.organization_service.OrganizationService.GetTeamMembers.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='members', full_name='main.organization_service.OrganizationService.GetTeamMembers.Response.members', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=813,
  serialized_end=840,
)

_ORGANIZATIONSERVICE_GETTEAMMEMBERS = _descriptor.Descriptor(
  name='GetTeamMembers',
  full_name='main.organization_service.OrganizationService.GetTeamMembers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ORGANIZATIONSERVICE_GETTEAMMEMBERS_REQUEST, _ORGANIZATIONSERVICE_GETTEAMMEMBERS_RESPONSE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=767,
  serialized_end=840,
)

_ORGANIZATIONSERVICE_ADDTEAMMEMBERS_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='main.organization_service.OrganizationService.AddTeamMembers.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_id', full_name='main.organization_service.OrganizationService.AddTeamMembers.Request.team_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_ids', full_name='main.organization_service.OrganizationService.AddTeamMembers.Request.user_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=860,
  serialized_end=904,
)

_ORGANIZATIONSERVICE_ADDTEAMMEMBERS_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='main.organization_service.OrganizationService.AddTeamMembers.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=329,
)

_ORGANIZATIONSERVICE_ADDTEAMMEMBERS = _descriptor.Descriptor(
  name='AddTeamMembers',
  full_name='main.organization_service.OrganizationService.AddTeamMembers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ORGANIZATIONSERVICE_ADDTEAMMEMBERS_REQUEST, _ORGANIZATIONSERVICE_ADDTEAMMEMBERS_RESPONSE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=842,
  serialized_end=916,
)

_ORGANIZATIONSERVICE_REMOVETEAMMEMBERS_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='main.organization_service.OrganizationService.RemoveTeamMembers.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_id', full_name='main.organization_service.OrganizationService.RemoveTeamMembers.Request.team_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_ids', full_name='main.organization_service.OrganizationService.RemoveTeamMembers.Request.user_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=860,
  serialized_end=904,
)

_ORGANIZATIONSERVICE_REMOVETEAMMEMBERS_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='main.organization_service.OrganizationService.RemoveTeamMembers.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=329,
)

_ORGANIZATIONSERVICE_REMOVETEAMMEMBERS = _descriptor.Descriptor(
  name='RemoveTeamMembers',
  full_name='main.organization_service.OrganizationService.RemoveTeamMembers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ORGANIZATIONSERVICE_REMOVETEAMMEMBERS_REQUEST, _ORGANIZATIONSERVICE_REMOVETEAMMEMBERS_RESPONSE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=918,
  serialized_end=995,
)

_ORGANIZATIONSERVICE = _descriptor.Descriptor(
  name='OrganizationService',
  full_name='main.organization_service.OrganizationService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ORGANIZATIONSERVICE_CONTAINERS, _ORGANIZATIONSERVICE_CREATEORGANIZATION, _ORGANIZATIONSERVICE_CREATETEAM, _ORGANIZATIONSERVICE_ADDTEAMMEMBER, _ORGANIZATIONSERVICE_REMOVETEAMMEMBER, _ORGANIZATIONSERVICE_GETTEAMMEMBERS, _ORGANIZATIONSERVICE_ADDTEAMMEMBERS, _ORGANIZATIONSERVICE_REMOVETEAMMEMBERS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=995,
)

_ORGANIZATIONSERVICE_CONTAINERS_ORGANIZATION.containing_type = _ORGANIZATIONSERVICE_CONTAINERS
_ORGANIZATIONSERVICE_CONTAINERS_TEAM.containing_type = _ORGANIZATIONSERVICE_CONTAINERS
_ORGANIZATIONSERVICE_CONTAINERS.containing_type = _ORGANIZATIONSERVICE
_ORGANIZATIONSERVICE_CREATEORGANIZATION_REQUEST.containing_type = _ORGANIZATIONSERVICE_CREATEORGANIZATION
_ORGANIZATIONSERVICE_CREATEORGANIZATION_RESPONSE.fields_by_name['organization'].message_type = _ORGANIZATIONSERVICE_CONTAINERS_ORGANIZATION
_ORGANIZATIONSERVICE_CREATEORGANIZATION_RESPONSE.containing_type = _ORGANIZATIONSERVICE_CREATEORGANIZATION
_ORGANIZATIONSERVICE_CREATEORGANIZATION.containing_type = _ORGANIZATIONSERVICE
_ORGANIZATIONSERVICE_CREATETEAM_REQUEST.containing_type = _ORGANIZATIONSERVICE_CREATETEAM
_ORGANIZATIONSERVICE_CREATETEAM_RESPONSE.fields_by_name['team'].message_type = _ORGANIZATIONSERVICE_CONTAINERS_TEAM
_ORGANIZATIONSERVICE_CREATETEAM_RESPONSE.containing_type = _ORGANIZATIONSERVICE_CREATETEAM
_ORGANIZATIONSERVICE_CREATETEAM.containing_type = _ORGANIZATIONSERVICE
_ORGANIZATIONSERVICE_ADDTEAMMEMBER_REQUEST.containing_type = _ORGANIZATIONSERVICE_ADDTEAMMEMBER
_ORGANIZATIONSERVICE_ADDTEAMMEMBER_RESPONSE.containing_type = _ORGANIZATIONSERVICE_ADDTEAMMEMBER
_ORGANIZATIONSERVICE_ADDTEAMMEMBER.containing_type = _ORGANIZATIONSERVICE
_ORGANIZATIONSERVICE_REMOVETEAMMEMBER_REQUEST.containing_type = _ORGANIZATIONSERVICE_REMOVETEAMMEMBER
_ORGANIZATIONSERVICE_REMOVETEAMMEMBER_RESPONSE.containing_type = _ORGANIZATIONSERVICE_REMOVETEAMMEMBER
_ORGANIZATIONSERVICE_REMOVETEAMMEMBER.containing_type = _ORGANIZATIONSERVICE
_ORGANIZATIONSERVICE_GETTEAMMEMBERS_REQUEST.containing_type = _ORGANIZATIONSERVICE_GETTEAMMEMBERS
_ORGANIZATIONSERVICE_GETTEAMMEMBERS_RESPONSE.containing_type = _ORGANIZATIONSERVICE_GETTEAMMEMBERS
_ORGANIZATIONSERVICE_GETTEAMMEMBERS.containing_type = _ORGANIZATIONSERVICE
_ORGANIZATIONSERVICE_ADDTEAMMEMBERS_REQUEST.containing_type = _ORGANIZATIONSERVICE_ADDTEAMMEMBERS
_ORGANIZATIONSERVICE_ADDTEAMMEMBERS_RESPONSE.containing_type = _ORGANIZATIONSERVICE_ADDTEAMMEMBERS
_ORGANIZATIONSERVICE_ADDTEAMMEMBERS.containing_type = _ORGANIZATIONSERVICE
_ORGANIZATIONSERVICE_REMOVETEAMMEMBERS_REQUEST.containing_type = _ORGANIZATIONSERVICE_REMOVETEAMMEMBERS
_ORGANIZATIONSERVICE_REMOVETEAMMEMBERS_RESPONSE.containing_type = _ORGANIZATIONSERVICE_REMOVETEAMMEMBERS
_ORGANIZATIONSERVICE_REMOVETEAMMEMBERS.containing_type = _ORGANIZATIONSERVICE
DESCRIPTOR.message_types_by_name['OrganizationService'] = _ORGANIZATIONSERVICE

OrganizationService = _reflection.GeneratedProtocolMessageType('OrganizationService', (_message.Message,), dict(

  Containers = _reflection.GeneratedProtocolMessageType('Containers', (_message.Message,), dict(

    Organization = _reflection.GeneratedProtocolMessageType('Organization', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_CONTAINERS_ORGANIZATION,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.Containers.Organization)
      ))
    ,

    Team = _reflection.GeneratedProtocolMessageType('Team', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_CONTAINERS_TEAM,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.Containers.Team)
      ))
    ,
    DESCRIPTOR = _ORGANIZATIONSERVICE_CONTAINERS,
    __module__ = 'protobufs.organization_service_pb2'
    # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.Containers)
    ))
  ,

  CreateOrganization = _reflection.GeneratedProtocolMessageType('CreateOrganization', (_message.Message,), dict(

    Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_CREATEORGANIZATION_REQUEST,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.CreateOrganization.Request)
      ))
    ,

    Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_CREATEORGANIZATION_RESPONSE,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.CreateOrganization.Response)
      ))
    ,
    DESCRIPTOR = _ORGANIZATIONSERVICE_CREATEORGANIZATION,
    __module__ = 'protobufs.organization_service_pb2'
    # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.CreateOrganization)
    ))
  ,

  CreateTeam = _reflection.GeneratedProtocolMessageType('CreateTeam', (_message.Message,), dict(

    Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_CREATETEAM_REQUEST,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.CreateTeam.Request)
      ))
    ,

    Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_CREATETEAM_RESPONSE,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.CreateTeam.Response)
      ))
    ,
    DESCRIPTOR = _ORGANIZATIONSERVICE_CREATETEAM,
    __module__ = 'protobufs.organization_service_pb2'
    # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.CreateTeam)
    ))
  ,

  AddTeamMember = _reflection.GeneratedProtocolMessageType('AddTeamMember', (_message.Message,), dict(

    Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_ADDTEAMMEMBER_REQUEST,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.AddTeamMember.Request)
      ))
    ,

    Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_ADDTEAMMEMBER_RESPONSE,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.AddTeamMember.Response)
      ))
    ,
    DESCRIPTOR = _ORGANIZATIONSERVICE_ADDTEAMMEMBER,
    __module__ = 'protobufs.organization_service_pb2'
    # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.AddTeamMember)
    ))
  ,

  RemoveTeamMember = _reflection.GeneratedProtocolMessageType('RemoveTeamMember', (_message.Message,), dict(

    Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_REMOVETEAMMEMBER_REQUEST,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.RemoveTeamMember.Request)
      ))
    ,

    Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_REMOVETEAMMEMBER_RESPONSE,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.RemoveTeamMember.Response)
      ))
    ,
    DESCRIPTOR = _ORGANIZATIONSERVICE_REMOVETEAMMEMBER,
    __module__ = 'protobufs.organization_service_pb2'
    # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.RemoveTeamMember)
    ))
  ,

  GetTeamMembers = _reflection.GeneratedProtocolMessageType('GetTeamMembers', (_message.Message,), dict(

    Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_GETTEAMMEMBERS_REQUEST,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.GetTeamMembers.Request)
      ))
    ,

    Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_GETTEAMMEMBERS_RESPONSE,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.GetTeamMembers.Response)
      ))
    ,
    DESCRIPTOR = _ORGANIZATIONSERVICE_GETTEAMMEMBERS,
    __module__ = 'protobufs.organization_service_pb2'
    # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.GetTeamMembers)
    ))
  ,

  AddTeamMembers = _reflection.GeneratedProtocolMessageType('AddTeamMembers', (_message.Message,), dict(

    Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_ADDTEAMMEMBERS_REQUEST,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.AddTeamMembers.Request)
      ))
    ,

    Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_ADDTEAMMEMBERS_RESPONSE,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.AddTeamMembers.Response)
      ))
    ,
    DESCRIPTOR = _ORGANIZATIONSERVICE_ADDTEAMMEMBERS,
    __module__ = 'protobufs.organization_service_pb2'
    # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.AddTeamMembers)
    ))
  ,

  RemoveTeamMembers = _reflection.GeneratedProtocolMessageType('RemoveTeamMembers', (_message.Message,), dict(

    Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_REMOVETEAMMEMBERS_REQUEST,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.RemoveTeamMembers.Request)
      ))
    ,

    Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
      DESCRIPTOR = _ORGANIZATIONSERVICE_REMOVETEAMMEMBERS_RESPONSE,
      __module__ = 'protobufs.organization_service_pb2'
      # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.RemoveTeamMembers.Response)
      ))
    ,
    DESCRIPTOR = _ORGANIZATIONSERVICE_REMOVETEAMMEMBERS,
    __module__ = 'protobufs.organization_service_pb2'
    # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService.RemoveTeamMembers)
    ))
  ,
  DESCRIPTOR = _ORGANIZATIONSERVICE,
  __module__ = 'protobufs.organization_service_pb2'
  # @@protoc_insertion_point(class_scope:main.organization_service.OrganizationService)
  ))
_sym_db.RegisterMessage(OrganizationService)
_sym_db.RegisterMessage(OrganizationService.Containers)
_sym_db.RegisterMessage(OrganizationService.Containers.Organization)
_sym_db.RegisterMessage(OrganizationService.Containers.Team)
_sym_db.RegisterMessage(OrganizationService.CreateOrganization)
_sym_db.RegisterMessage(OrganizationService.CreateOrganization.Request)
_sym_db.RegisterMessage(OrganizationService.CreateOrganization.Response)
_sym_db.RegisterMessage(OrganizationService.CreateTeam)
_sym_db.RegisterMessage(OrganizationService.CreateTeam.Request)
_sym_db.RegisterMessage(OrganizationService.CreateTeam.Response)
_sym_db.RegisterMessage(OrganizationService.AddTeamMember)
_sym_db.RegisterMessage(OrganizationService.AddTeamMember.Request)
_sym_db.RegisterMessage(OrganizationService.AddTeamMember.Response)
_sym_db.RegisterMessage(OrganizationService.RemoveTeamMember)
_sym_db.RegisterMessage(OrganizationService.RemoveTeamMember.Request)
_sym_db.RegisterMessage(OrganizationService.RemoveTeamMember.Response)
_sym_db.RegisterMessage(OrganizationService.GetTeamMembers)
_sym_db.RegisterMessage(OrganizationService.GetTeamMembers.Request)
_sym_db.RegisterMessage(OrganizationService.GetTeamMembers.Response)
_sym_db.RegisterMessage(OrganizationService.AddTeamMembers)
_sym_db.RegisterMessage(OrganizationService.AddTeamMembers.Request)
_sym_db.RegisterMessage(OrganizationService.AddTeamMembers.Response)
_sym_db.RegisterMessage(OrganizationService.RemoveTeamMembers)
_sym_db.RegisterMessage(OrganizationService.RemoveTeamMembers.Request)
_sym_db.RegisterMessage(OrganizationService.RemoveTeamMembers.Response)


# @@protoc_insertion_point(module_scope)
