# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/response_registry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import service.protobufs.common.soa_pb2
import protobufs.credential_service.create_credentials_pb2
import protobufs.credential_service.verify_credentials_pb2
import protobufs.credential_service.update_credentials_pb2
import protobufs.identity_service.create_identity_pb2
import protobufs.identity_service.get_identity_pb2
import protobufs.user_service.create_user_pb2
import protobufs.user_service.valid_user_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/response_registry.proto',
  package='main.responses',
  serialized_pb=_b('\n!protobufs/response_registry.proto\x12\x0emain.responses\x1a\"service/protobufs/common/soa.proto\x1a\x35protobufs/credential_service/create_credentials.proto\x1a\x35protobufs/credential_service/verify_credentials.proto\x1a\x35protobufs/credential_service/update_credentials.proto\x1a\x30protobufs/identity_service/create_identity.proto\x1a-protobufs/identity_service/get_identity.proto\x1a(protobufs/user_service/create_user.proto\x1a\'protobufs/user_service/valid_user.proto\"\xbd\x01\n\x0bUserService2W\n\x0b\x63reate_user\x12\x19.soa.ActionResponseResult\x18\x65 \x01(\x0b\x32\'.main.user_service.create_user.Response2U\n\nvalid_user\x12\x19.soa.ActionResponseResult\x18\x66 \x01(\x0b\x32&.main.user_service.valid_user.Response\"\xd5\x01\n\x0fIdentityService2c\n\x0f\x63reate_identity\x12\x19.soa.ActionResponseResult\x18g \x01(\x0b\x32/.main.identity_service.create_identity.Response2]\n\x0cget_identity\x12\x19.soa.ActionResponseResult\x18h \x01(\x0b\x32,.main.identity_service.get_identity.Response\"\xda\x02\n\x11\x43redentialService2k\n\x12\x63reate_credentials\x12\x19.soa.ActionResponseResult\x18i \x01(\x0b\x32\x34.main.credential_service.create_credentials.Response2k\n\x12verify_credentials\x12\x19.soa.ActionResponseResult\x18j \x01(\x0b\x32\x34.main.credential_service.verify_credentials.Response2k\n\x12update_credentials\x12\x19.soa.ActionResponseResult\x18k \x01(\x0b\x32\x34.main.credential_service.update_credentials.Response')
  ,
  dependencies=[service.protobufs.common.soa_pb2.DESCRIPTOR,protobufs.credential_service.create_credentials_pb2.DESCRIPTOR,protobufs.credential_service.verify_credentials_pb2.DESCRIPTOR,protobufs.credential_service.update_credentials_pb2.DESCRIPTOR,protobufs.identity_service.create_identity_pb2.DESCRIPTOR,protobufs.identity_service.get_identity_pb2.DESCRIPTOR,protobufs.user_service.create_user_pb2.DESCRIPTOR,protobufs.user_service.valid_user_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USERSERVICE = _descriptor.Descriptor(
  name='UserService',
  full_name='main.responses.UserService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='create_user', full_name='main.responses.UserService.create_user', index=0,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valid_user', full_name='main.responses.UserService.valid_user', index=1,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=624,
)


_IDENTITYSERVICE = _descriptor.Descriptor(
  name='IdentityService',
  full_name='main.responses.IdentityService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='create_identity', full_name='main.responses.IdentityService.create_identity', index=0,
      number=103, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_identity', full_name='main.responses.IdentityService.get_identity', index=1,
      number=104, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=627,
  serialized_end=840,
)


_CREDENTIALSERVICE = _descriptor.Descriptor(
  name='CredentialService',
  full_name='main.responses.CredentialService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='create_credentials', full_name='main.responses.CredentialService.create_credentials', index=0,
      number=105, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='verify_credentials', full_name='main.responses.CredentialService.verify_credentials', index=1,
      number=106, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='update_credentials', full_name='main.responses.CredentialService.update_credentials', index=2,
      number=107, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=843,
  serialized_end=1189,
)

DESCRIPTOR.message_types_by_name['UserService'] = _USERSERVICE
DESCRIPTOR.message_types_by_name['IdentityService'] = _IDENTITYSERVICE
DESCRIPTOR.message_types_by_name['CredentialService'] = _CREDENTIALSERVICE

UserService = _reflection.GeneratedProtocolMessageType('UserService', (_message.Message,), dict(
  DESCRIPTOR = _USERSERVICE,
  __module__ = 'protobufs.response_registry_pb2'
  # @@protoc_insertion_point(class_scope:main.responses.UserService)
  ))
_sym_db.RegisterMessage(UserService)

IdentityService = _reflection.GeneratedProtocolMessageType('IdentityService', (_message.Message,), dict(
  DESCRIPTOR = _IDENTITYSERVICE,
  __module__ = 'protobufs.response_registry_pb2'
  # @@protoc_insertion_point(class_scope:main.responses.IdentityService)
  ))
_sym_db.RegisterMessage(IdentityService)

CredentialService = _reflection.GeneratedProtocolMessageType('CredentialService', (_message.Message,), dict(
  DESCRIPTOR = _CREDENTIALSERVICE,
  __module__ = 'protobufs.response_registry_pb2'
  # @@protoc_insertion_point(class_scope:main.responses.CredentialService)
  ))
_sym_db.RegisterMessage(CredentialService)

_USERSERVICE.extensions_by_name['create_user'].message_type = protobufs.user_service.create_user_pb2._RESPONSE
service.protobufs.common.soa_pb2.ActionResponseResult.RegisterExtension(_USERSERVICE.extensions_by_name['create_user'])
_USERSERVICE.extensions_by_name['valid_user'].message_type = protobufs.user_service.valid_user_pb2._RESPONSE
service.protobufs.common.soa_pb2.ActionResponseResult.RegisterExtension(_USERSERVICE.extensions_by_name['valid_user'])
_IDENTITYSERVICE.extensions_by_name['create_identity'].message_type = protobufs.identity_service.create_identity_pb2._RESPONSE
service.protobufs.common.soa_pb2.ActionResponseResult.RegisterExtension(_IDENTITYSERVICE.extensions_by_name['create_identity'])
_IDENTITYSERVICE.extensions_by_name['get_identity'].message_type = protobufs.identity_service.get_identity_pb2._RESPONSE
service.protobufs.common.soa_pb2.ActionResponseResult.RegisterExtension(_IDENTITYSERVICE.extensions_by_name['get_identity'])
_CREDENTIALSERVICE.extensions_by_name['create_credentials'].message_type = protobufs.credential_service.create_credentials_pb2._RESPONSE
service.protobufs.common.soa_pb2.ActionResponseResult.RegisterExtension(_CREDENTIALSERVICE.extensions_by_name['create_credentials'])
_CREDENTIALSERVICE.extensions_by_name['verify_credentials'].message_type = protobufs.credential_service.verify_credentials_pb2._RESPONSE
service.protobufs.common.soa_pb2.ActionResponseResult.RegisterExtension(_CREDENTIALSERVICE.extensions_by_name['verify_credentials'])
_CREDENTIALSERVICE.extensions_by_name['update_credentials'].message_type = protobufs.credential_service.update_credentials_pb2._RESPONSE
service.protobufs.common.soa_pb2.ActionResponseResult.RegisterExtension(_CREDENTIALSERVICE.extensions_by_name['update_credentials'])

# @@protoc_insertion_point(module_scope)
