// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./src/protobufs/services/group/containers/permissions/who_can_invite.proto
package com.rhlabs.protobufs.services.group.containers.permissions.who_can_invite;

import com.squareup.wire.ProtoEnum;

public enum WhoCanInvitePermissionsV1
    implements ProtoEnum {
  ALL_MEMBERS(0),
  ALL_MANAGERS(1);

  private final int value;

  WhoCanInvitePermissionsV1(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
