// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./src/protobufs/services/user/containers/token.proto
package com.rhlabs.protobufs.services.user.containers.token;

import com.squareup.wire.ProtoEnum;

public enum ClientTypeV1
    implements ProtoEnum {
  IOS(0),
  ANDROID(1),
  WEB(2),
  API(3);

  private final int value;

  ClientTypeV1(int value) {
    this.value = value;
  }

  @Override
  public int getValue() {
    return value;
  }
}
