// Generated by the protocol buffer compiler.  DO NOT EDIT!

import Foundation
import ProtocolBuffers


internal extension Services.Profile.Actions{ internal struct GetUpcomingAnniversaries { }}

internal func == (lhs: Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1, rhs: Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasVersion == rhs.hasVersion) && (!lhs.hasVersion || lhs.version == rhs.version)
  fieldCheck = fieldCheck && (lhs.hasOrganizationId == rhs.hasOrganizationId) && (!lhs.hasOrganizationId || lhs.organizationId == rhs.organizationId)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal func == (lhs: Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1, rhs: Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasVersion == rhs.hasVersion) && (!lhs.hasVersion || lhs.version == rhs.version)
  fieldCheck = fieldCheck && (lhs.profiles == rhs.profiles)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal extension Services.Profile.Actions.GetUpcomingAnniversaries {
  internal struct GetUpcomingAnniversariesRoot {
    internal static var sharedInstance : GetUpcomingAnniversariesRoot {
     struct Static {
         static let instance : GetUpcomingAnniversariesRoot = GetUpcomingAnniversariesRoot()
     }
     return Static.instance
    }
    internal var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
      Services.Profile.Containers.Profile.ProfileRoot.sharedInstance.registerAllExtensions(extensionRegistry)
    }
    internal func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final internal class RequestV1 : GeneratedMessage, GeneratedMessageProtocol {
    private(set) var hasVersion:Bool = false
    private(set) var version:UInt32 = UInt32(1)

    private(set) var hasOrganizationId:Bool = false
    private(set) var organizationId:String = ""

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasVersion {
        output.writeUInt32(1, value:version)
      }
      if hasOrganizationId {
        output.writeString(2, value:organizationId)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasVersion {
        serialize_size += version.computeUInt32Size(1)
      }
      if hasOrganizationId {
        serialize_size += organizationId.computeStringSize(2)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1 {
      return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1.builder().mergeFromData(data, extensionRegistry:Services.Profile.Actions.GetUpcomingAnniversaries.GetUpcomingAnniversariesRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1 {
      return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1 {
      return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) ->Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1 {
      return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1 {
      return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1 {
      return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder {
      return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1.classBuilder() as! Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder
    }
    internal func builder() -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder {
      return classBuilder() as! Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1.builder()
    }
    internal func toBuilder() -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder {
      return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1) -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder {
      return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasVersion {
        output += "\(indent) version: \(version) \n"
      }
      if hasOrganizationId {
        output += "\(indent) organizationId: \(organizationId) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasVersion {
               hashCode = (hashCode &* 31) &+ version.hashValue
            }
            if hasOrganizationId {
               hashCode = (hashCode &* 31) &+ organizationId.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1"
    }
    override internal func className() -> String {
        return "Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1.self
    }
    //Meta information declaration end

  }

  final internal class RequestV1Builder : GeneratedMessageBuilder {
    private var builderResult:Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1

    required override internal init () {
       builderResult = Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1()
       super.init()
    }
    var hasVersion:Bool {
         get {
              return builderResult.hasVersion
         }
    }
    var version:UInt32 {
         get {
              return builderResult.version
         }
         set (value) {
             builderResult.hasVersion = true
             builderResult.version = value
         }
    }
    func setVersion(value:UInt32)-> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder {
      self.version = value
      return self
    }
    internal func clearVersion() -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder{
         builderResult.hasVersion = false
         builderResult.version = UInt32(1)
         return self
    }
    var hasOrganizationId:Bool {
         get {
              return builderResult.hasOrganizationId
         }
    }
    var organizationId:String {
         get {
              return builderResult.organizationId
         }
         set (value) {
             builderResult.hasOrganizationId = true
             builderResult.organizationId = value
         }
    }
    func setOrganizationId(value:String)-> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder {
      self.organizationId = value
      return self
    }
    internal func clearOrganizationId() -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder{
         builderResult.hasOrganizationId = false
         builderResult.organizationId = ""
         return self
    }
    override internal var internalGetResult:GeneratedMessage {
         get {
            return builderResult
         }
    }
    internal override func clear() -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder {
      builderResult = Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1()
      return self
    }
    internal override func clone() -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder {
      return Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1.builderWithPrototype(builderResult)
    }
    internal override func build() -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1 {
         checkInitialized()
         return buildPartial()
    }
    internal func buildPartial() -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1 {
      var returnMe:Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1 = builderResult
      return returnMe
    }
    internal func mergeFrom(other:Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1) -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder {
      if (other == Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1()) {
       return self
      }
      if other.hasVersion {
           version = other.version
      }
      if other.hasOrganizationId {
           organizationId = other.organizationId
      }
      mergeUnknownFields(other.unknownFields)
      return self
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream) ->Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder {
         return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Services.Profile.Actions.GetUpcomingAnniversaries.RequestV1Builder {
      var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
      while (true) {
        var tag = input.readTag()
        switch tag {
        case 0: 
          self.unknownFields = unknownFieldsBuilder.build()
          return self

        case 8 :
          version = input.readUInt32()

        case 18 :
          organizationId = input.readString()

        default:
          if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
             unknownFields = unknownFieldsBuilder.build()
             return self
          }
        }
      }
    }
  }

  final internal class ResponseV1 : GeneratedMessage, GeneratedMessageProtocol {
    private(set) var hasVersion:Bool = false
    private(set) var version:UInt32 = UInt32(1)

    private(set) var profiles:Array<Services.Profile.Containers.Profile.ProfileV1>  = Array<Services.Profile.Containers.Profile.ProfileV1>()
    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasVersion {
        output.writeUInt32(1, value:version)
      }
      for oneElementprofiles in profiles {
          output.writeMessage(2, value:oneElementprofiles)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasVersion {
        serialize_size += version.computeUInt32Size(1)
      }
      for oneElementprofiles in profiles {
          serialize_size += oneElementprofiles.computeMessageSize(2)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1 {
      return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1.builder().mergeFromData(data, extensionRegistry:Services.Profile.Actions.GetUpcomingAnniversaries.GetUpcomingAnniversariesRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1 {
      return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1 {
      return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) ->Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1 {
      return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1 {
      return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1 {
      return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder {
      return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1.classBuilder() as! Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder
    }
    internal func builder() -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder {
      return classBuilder() as! Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1.builder()
    }
    internal func toBuilder() -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder {
      return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1) -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder {
      return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasVersion {
        output += "\(indent) version: \(version) \n"
      }
      var profilesElementIndex:Int = 0
      for oneElementprofiles in profiles {
          output += "\(indent) profiles[\(profilesElementIndex)] {\n"
          oneElementprofiles.writeDescriptionTo(&output, indent:"\(indent)  ")
          output += "\(indent)}\n"
          profilesElementIndex++
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasVersion {
               hashCode = (hashCode &* 31) &+ version.hashValue
            }
            for oneElementprofiles in profiles {
                hashCode = (hashCode &* 31) &+ oneElementprofiles.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1"
    }
    override internal func className() -> String {
        return "Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1.self
    }
    //Meta information declaration end

  }

  final internal class ResponseV1Builder : GeneratedMessageBuilder {
    private var builderResult:Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1

    required override internal init () {
       builderResult = Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1()
       super.init()
    }
    var hasVersion:Bool {
         get {
              return builderResult.hasVersion
         }
    }
    var version:UInt32 {
         get {
              return builderResult.version
         }
         set (value) {
             builderResult.hasVersion = true
             builderResult.version = value
         }
    }
    func setVersion(value:UInt32)-> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder {
      self.version = value
      return self
    }
    internal func clearVersion() -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder{
         builderResult.hasVersion = false
         builderResult.version = UInt32(1)
         return self
    }
    var profiles:Array<Services.Profile.Containers.Profile.ProfileV1> {
         get {
             return builderResult.profiles
         }
         set (value) {
             builderResult.profiles = value
         }
    }
    func setProfiles(value:Array<Services.Profile.Containers.Profile.ProfileV1>)-> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder {
      self.profiles = value
      return self
    }
    internal func clearProfiles() -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder {
      builderResult.profiles.removeAll(keepCapacity: false)
      return self
    }
    override internal var internalGetResult:GeneratedMessage {
         get {
            return builderResult
         }
    }
    internal override func clear() -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder {
      builderResult = Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1()
      return self
    }
    internal override func clone() -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder {
      return Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1.builderWithPrototype(builderResult)
    }
    internal override func build() -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1 {
         checkInitialized()
         return buildPartial()
    }
    internal func buildPartial() -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1 {
      var returnMe:Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1 = builderResult
      return returnMe
    }
    internal func mergeFrom(other:Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1) -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder {
      if (other == Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1()) {
       return self
      }
      if other.hasVersion {
           version = other.version
      }
      if !other.profiles.isEmpty  {
         builderResult.profiles += other.profiles
      }
      mergeUnknownFields(other.unknownFields)
      return self
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream) ->Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder {
         return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Services.Profile.Actions.GetUpcomingAnniversaries.ResponseV1Builder {
      var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
      while (true) {
        var tag = input.readTag()
        switch tag {
        case 0: 
          self.unknownFields = unknownFieldsBuilder.build()
          return self

        case 8 :
          version = input.readUInt32()

        case 18 :
          var subBuilder = Services.Profile.Containers.Profile.ProfileV1.builder()
          input.readMessage(subBuilder,extensionRegistry:extensionRegistry)
          profiles += [subBuilder.buildPartial()]

        default:
          if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
             unknownFields = unknownFieldsBuilder.build()
             return self
          }
        }
      }
    }
  }

}

// @@protoc_insertion_point(global_scope)
