// Generated by the protocol buffer compiler.  DO NOT EDIT!

import Foundation
public extension Services.User.Actions{ public struct VerifyVerificationCode { }}

public func == (lhs: Services.User.Actions.VerifyVerificationCode.RequestV1, rhs: Services.User.Actions.VerifyVerificationCode.RequestV1) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasVersion == rhs.hasVersion) && (!lhs.hasVersion || lhs.version == rhs.version)
  fieldCheck = fieldCheck && (lhs.hasUserId == rhs.hasUserId) && (!lhs.hasUserId || lhs.userId == rhs.userId)
  fieldCheck = fieldCheck && (lhs.hasCode == rhs.hasCode) && (!lhs.hasCode || lhs.code == rhs.code)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

public func == (lhs: Services.User.Actions.VerifyVerificationCode.ResponseV1, rhs: Services.User.Actions.VerifyVerificationCode.ResponseV1) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasVersion == rhs.hasVersion) && (!lhs.hasVersion || lhs.version == rhs.version)
  fieldCheck = fieldCheck && (lhs.hasVerified == rhs.hasVerified) && (!lhs.hasVerified || lhs.verified == rhs.verified)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

public extension Services.User.Actions.VerifyVerificationCode {
  public struct VerifyVerificationCodeRoot {
    public static var sharedInstance : VerifyVerificationCodeRoot {
     struct Static {
         static let instance : VerifyVerificationCodeRoot = VerifyVerificationCodeRoot()
     }
     return Static.instance
    }
    public var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    public func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final public class RequestV1 : GeneratedMessage, GeneratedMessageProtocol {
    public subscript(key: String) -> Any? {
           switch key {
           case "version": return version
           case "userId": return userId
           case "code": return code
           default: return nil
           }
    }

    public private(set) var hasVersion:Bool = false
    public private(set) var version:UInt32 = UInt32(1)

    public private(set) var hasUserId:Bool = false
    public private(set) var userId:String = ""

    public private(set) var hasCode:Bool = false
    public private(set) var code:String = ""

    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasVersion {
        output.writeUInt32(1, value:version)
      }
      if hasUserId {
        output.writeString(2, value:userId)
      }
      if hasCode {
        output.writeString(3, value:code)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasVersion {
        serialize_size += version.computeUInt32Size(1)
      }
      if hasUserId {
        serialize_size += userId.computeStringSize(2)
      }
      if hasCode {
        serialize_size += code.computeStringSize(3)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseFromData(data:NSData) -> Services.User.Actions.VerifyVerificationCode.RequestV1 {
      return Services.User.Actions.VerifyVerificationCode.RequestV1.builder().mergeFromData(data, extensionRegistry:Services.User.Actions.VerifyVerificationCode.VerifyVerificationCodeRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Services.User.Actions.VerifyVerificationCode.RequestV1 {
      return Services.User.Actions.VerifyVerificationCode.RequestV1.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) -> Services.User.Actions.VerifyVerificationCode.RequestV1 {
      return Services.User.Actions.VerifyVerificationCode.RequestV1.builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) ->Services.User.Actions.VerifyVerificationCode.RequestV1 {
      return Services.User.Actions.VerifyVerificationCode.RequestV1.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) -> Services.User.Actions.VerifyVerificationCode.RequestV1 {
      return Services.User.Actions.VerifyVerificationCode.RequestV1.builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Services.User.Actions.VerifyVerificationCode.RequestV1 {
      return Services.User.Actions.VerifyVerificationCode.RequestV1.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func builder() -> Services.User.Actions.VerifyVerificationCode.RequestV1Builder {
      return Services.User.Actions.VerifyVerificationCode.RequestV1.classBuilder() as! Services.User.Actions.VerifyVerificationCode.RequestV1Builder
    }
    public func builder() -> Services.User.Actions.VerifyVerificationCode.RequestV1Builder {
      return classBuilder() as! Services.User.Actions.VerifyVerificationCode.RequestV1Builder
    }
    public override class func classBuilder() -> MessageBuilder {
      return Services.User.Actions.VerifyVerificationCode.RequestV1Builder()
    }
    public override func classBuilder() -> MessageBuilder {
      return Services.User.Actions.VerifyVerificationCode.RequestV1.builder()
    }
    public func toBuilder() -> Services.User.Actions.VerifyVerificationCode.RequestV1Builder {
      return Services.User.Actions.VerifyVerificationCode.RequestV1.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Services.User.Actions.VerifyVerificationCode.RequestV1) -> Services.User.Actions.VerifyVerificationCode.RequestV1Builder {
      return Services.User.Actions.VerifyVerificationCode.RequestV1.builder().mergeFrom(prototype)
    }
    override public func writeDescriptionTo(inout output:String, indent:String) {
      if hasVersion {
        output += "\(indent) version: \(version) \n"
      }
      if hasUserId {
        output += "\(indent) userId: \(userId) \n"
      }
      if hasCode {
        output += "\(indent) code: \(code) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasVersion {
               hashCode = (hashCode &* 31) &+ version.hashValue
            }
            if hasUserId {
               hashCode = (hashCode &* 31) &+ userId.hashValue
            }
            if hasCode {
               hashCode = (hashCode &* 31) &+ code.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Services.User.Actions.VerifyVerificationCode.RequestV1"
    }
    override public func className() -> String {
        return "Services.User.Actions.VerifyVerificationCode.RequestV1"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Services.User.Actions.VerifyVerificationCode.RequestV1.self
    }
    //Meta information declaration end

  }

  final public class RequestV1Builder : GeneratedMessageBuilder {
    private var builderResult:Services.User.Actions.VerifyVerificationCode.RequestV1

    required override public init () {
       builderResult = Services.User.Actions.VerifyVerificationCode.RequestV1()
       super.init()
    }
    public var hasVersion:Bool {
         get {
              return builderResult.hasVersion
         }
    }
    public var version:UInt32 {
         get {
              return builderResult.version
         }
         set (value) {
             builderResult.hasVersion = true
             builderResult.version = value
         }
    }
    public func setVersion(value:UInt32)-> Services.User.Actions.VerifyVerificationCode.RequestV1Builder {
      self.version = value
      return self
    }
    public func clearVersion() -> Services.User.Actions.VerifyVerificationCode.RequestV1Builder{
         builderResult.hasVersion = false
         builderResult.version = UInt32(1)
         return self
    }
    public var hasUserId:Bool {
         get {
              return builderResult.hasUserId
         }
    }
    public var userId:String {
         get {
              return builderResult.userId
         }
         set (value) {
             builderResult.hasUserId = true
             builderResult.userId = value
         }
    }
    public func setUserId(value:String)-> Services.User.Actions.VerifyVerificationCode.RequestV1Builder {
      self.userId = value
      return self
    }
    public func clearUserId() -> Services.User.Actions.VerifyVerificationCode.RequestV1Builder{
         builderResult.hasUserId = false
         builderResult.userId = ""
         return self
    }
    public var hasCode:Bool {
         get {
              return builderResult.hasCode
         }
    }
    public var code:String {
         get {
              return builderResult.code
         }
         set (value) {
             builderResult.hasCode = true
             builderResult.code = value
         }
    }
    public func setCode(value:String)-> Services.User.Actions.VerifyVerificationCode.RequestV1Builder {
      self.code = value
      return self
    }
    public func clearCode() -> Services.User.Actions.VerifyVerificationCode.RequestV1Builder{
         builderResult.hasCode = false
         builderResult.code = ""
         return self
    }
    override public var internalGetResult:GeneratedMessage {
         get {
            return builderResult
         }
    }
    public override func clear() -> Services.User.Actions.VerifyVerificationCode.RequestV1Builder {
      builderResult = Services.User.Actions.VerifyVerificationCode.RequestV1()
      return self
    }
    public override func clone() -> Services.User.Actions.VerifyVerificationCode.RequestV1Builder {
      return Services.User.Actions.VerifyVerificationCode.RequestV1.builderWithPrototype(builderResult)
    }
    public override func build() -> Services.User.Actions.VerifyVerificationCode.RequestV1 {
         checkInitialized()
         return buildPartial()
    }
    public func buildPartial() -> Services.User.Actions.VerifyVerificationCode.RequestV1 {
      var returnMe:Services.User.Actions.VerifyVerificationCode.RequestV1 = builderResult
      return returnMe
    }
    public func mergeFrom(other:Services.User.Actions.VerifyVerificationCode.RequestV1) -> Services.User.Actions.VerifyVerificationCode.RequestV1Builder {
      if (other == Services.User.Actions.VerifyVerificationCode.RequestV1()) {
       return self
      }
      if other.hasVersion {
           version = other.version
      }
      if other.hasUserId {
           userId = other.userId
      }
      if other.hasCode {
           code = other.code
      }
      mergeUnknownFields(other.unknownFields)
      return self
    }
    public override func mergeFromCodedInputStream(input:CodedInputStream) ->Services.User.Actions.VerifyVerificationCode.RequestV1Builder {
         return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
    }
    public override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Services.User.Actions.VerifyVerificationCode.RequestV1Builder {
      var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
      while (true) {
        var tag = input.readTag()
        switch tag {
        case 0: 
          self.unknownFields = unknownFieldsBuilder.build()
          return self

        case 8 :
          version = input.readUInt32()

        case 18 :
          userId = input.readString()

        case 26 :
          code = input.readString()

        default:
          if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
             unknownFields = unknownFieldsBuilder.build()
             return self
          }
        }
      }
    }
  }

  final public class ResponseV1 : GeneratedMessage, GeneratedMessageProtocol {
    public subscript(key: String) -> Any? {
           switch key {
           case "version": return version
           case "verified": return verified
           default: return nil
           }
    }

    public private(set) var hasVersion:Bool = false
    public private(set) var version:UInt32 = UInt32(1)

    public private(set) var hasVerified:Bool = false
    public private(set) var verified:Bool = false

    required public init() {
         super.init()
    }
    override public func isInitialized() -> Bool {
     return true
    }
    override public func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasVersion {
        output.writeUInt32(1, value:version)
      }
      if hasVerified {
        output.writeBool(2, value:verified)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override public func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasVersion {
        serialize_size += version.computeUInt32Size(1)
      }
      if hasVerified {
        serialize_size += verified.computeBoolSize(2)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    public class func parseFromData(data:NSData) -> Services.User.Actions.VerifyVerificationCode.ResponseV1 {
      return Services.User.Actions.VerifyVerificationCode.ResponseV1.builder().mergeFromData(data, extensionRegistry:Services.User.Actions.VerifyVerificationCode.VerifyVerificationCodeRoot.sharedInstance.extensionRegistry).build()
    }
    public class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Services.User.Actions.VerifyVerificationCode.ResponseV1 {
      return Services.User.Actions.VerifyVerificationCode.ResponseV1.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromInputStream(input:NSInputStream) -> Services.User.Actions.VerifyVerificationCode.ResponseV1 {
      return Services.User.Actions.VerifyVerificationCode.ResponseV1.builder().mergeFromInputStream(input).build()
    }
    public class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) ->Services.User.Actions.VerifyVerificationCode.ResponseV1 {
      return Services.User.Actions.VerifyVerificationCode.ResponseV1.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream) -> Services.User.Actions.VerifyVerificationCode.ResponseV1 {
      return Services.User.Actions.VerifyVerificationCode.ResponseV1.builder().mergeFromCodedInputStream(input).build()
    }
    public class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Services.User.Actions.VerifyVerificationCode.ResponseV1 {
      return Services.User.Actions.VerifyVerificationCode.ResponseV1.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    public class func builder() -> Services.User.Actions.VerifyVerificationCode.ResponseV1Builder {
      return Services.User.Actions.VerifyVerificationCode.ResponseV1.classBuilder() as! Services.User.Actions.VerifyVerificationCode.ResponseV1Builder
    }
    public func builder() -> Services.User.Actions.VerifyVerificationCode.ResponseV1Builder {
      return classBuilder() as! Services.User.Actions.VerifyVerificationCode.ResponseV1Builder
    }
    public override class func classBuilder() -> MessageBuilder {
      return Services.User.Actions.VerifyVerificationCode.ResponseV1Builder()
    }
    public override func classBuilder() -> MessageBuilder {
      return Services.User.Actions.VerifyVerificationCode.ResponseV1.builder()
    }
    public func toBuilder() -> Services.User.Actions.VerifyVerificationCode.ResponseV1Builder {
      return Services.User.Actions.VerifyVerificationCode.ResponseV1.builderWithPrototype(self)
    }
    public class func builderWithPrototype(prototype:Services.User.Actions.VerifyVerificationCode.ResponseV1) -> Services.User.Actions.VerifyVerificationCode.ResponseV1Builder {
      return Services.User.Actions.VerifyVerificationCode.ResponseV1.builder().mergeFrom(prototype)
    }
    override public func writeDescriptionTo(inout output:String, indent:String) {
      if hasVersion {
        output += "\(indent) version: \(version) \n"
      }
      if hasVerified {
        output += "\(indent) verified: \(verified) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override public var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasVersion {
               hashCode = (hashCode &* 31) &+ version.hashValue
            }
            if hasVerified {
               hashCode = (hashCode &* 31) &+ verified.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override public class func className() -> String {
        return "Services.User.Actions.VerifyVerificationCode.ResponseV1"
    }
    override public func className() -> String {
        return "Services.User.Actions.VerifyVerificationCode.ResponseV1"
    }
    override public func classMetaType() -> GeneratedMessage.Type {
        return Services.User.Actions.VerifyVerificationCode.ResponseV1.self
    }
    //Meta information declaration end

  }

  final public class ResponseV1Builder : GeneratedMessageBuilder {
    private var builderResult:Services.User.Actions.VerifyVerificationCode.ResponseV1

    required override public init () {
       builderResult = Services.User.Actions.VerifyVerificationCode.ResponseV1()
       super.init()
    }
    public var hasVersion:Bool {
         get {
              return builderResult.hasVersion
         }
    }
    public var version:UInt32 {
         get {
              return builderResult.version
         }
         set (value) {
             builderResult.hasVersion = true
             builderResult.version = value
         }
    }
    public func setVersion(value:UInt32)-> Services.User.Actions.VerifyVerificationCode.ResponseV1Builder {
      self.version = value
      return self
    }
    public func clearVersion() -> Services.User.Actions.VerifyVerificationCode.ResponseV1Builder{
         builderResult.hasVersion = false
         builderResult.version = UInt32(1)
         return self
    }
    public var hasVerified:Bool {
         get {
              return builderResult.hasVerified
         }
    }
    public var verified:Bool {
         get {
              return builderResult.verified
         }
         set (value) {
             builderResult.hasVerified = true
             builderResult.verified = value
         }
    }
    public func setVerified(value:Bool)-> Services.User.Actions.VerifyVerificationCode.ResponseV1Builder {
      self.verified = value
      return self
    }
    public func clearVerified() -> Services.User.Actions.VerifyVerificationCode.ResponseV1Builder{
         builderResult.hasVerified = false
         builderResult.verified = false
         return self
    }
    override public var internalGetResult:GeneratedMessage {
         get {
            return builderResult
         }
    }
    public override func clear() -> Services.User.Actions.VerifyVerificationCode.ResponseV1Builder {
      builderResult = Services.User.Actions.VerifyVerificationCode.ResponseV1()
      return self
    }
    public override func clone() -> Services.User.Actions.VerifyVerificationCode.ResponseV1Builder {
      return Services.User.Actions.VerifyVerificationCode.ResponseV1.builderWithPrototype(builderResult)
    }
    public override func build() -> Services.User.Actions.VerifyVerificationCode.ResponseV1 {
         checkInitialized()
         return buildPartial()
    }
    public func buildPartial() -> Services.User.Actions.VerifyVerificationCode.ResponseV1 {
      var returnMe:Services.User.Actions.VerifyVerificationCode.ResponseV1 = builderResult
      return returnMe
    }
    public func mergeFrom(other:Services.User.Actions.VerifyVerificationCode.ResponseV1) -> Services.User.Actions.VerifyVerificationCode.ResponseV1Builder {
      if (other == Services.User.Actions.VerifyVerificationCode.ResponseV1()) {
       return self
      }
      if other.hasVersion {
           version = other.version
      }
      if other.hasVerified {
           verified = other.verified
      }
      mergeUnknownFields(other.unknownFields)
      return self
    }
    public override func mergeFromCodedInputStream(input:CodedInputStream) ->Services.User.Actions.VerifyVerificationCode.ResponseV1Builder {
         return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
    }
    public override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Services.User.Actions.VerifyVerificationCode.ResponseV1Builder {
      var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
      while (true) {
        var tag = input.readTag()
        switch tag {
        case 0: 
          self.unknownFields = unknownFieldsBuilder.build()
          return self

        case 8 :
          version = input.readUInt32()

        case 16 :
          verified = input.readBool()

        default:
          if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
             unknownFields = unknownFieldsBuilder.build()
             return self
          }
        }
      }
    }
  }

}

// @@protoc_insertion_point(global_scope)
