// Generated by the protocol buffer compiler.  DO NOT EDIT!

import Foundation
import ProtocolBuffers


internal extension Services.User.Containers{ internal struct User { }}

internal func == (lhs: Services.User.Containers.User.UserV1, rhs: Services.User.Containers.User.UserV1) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasVersion == rhs.hasVersion) && (!lhs.hasVersion || lhs.version == rhs.version)
  fieldCheck = fieldCheck && (lhs.hasId == rhs.hasId) && (!lhs.hasId || lhs.id == rhs.id)
  fieldCheck = fieldCheck && (lhs.hasPrimaryEmail == rhs.hasPrimaryEmail) && (!lhs.hasPrimaryEmail || lhs.primaryEmail == rhs.primaryEmail)
  fieldCheck = fieldCheck && (lhs.hasIsAdmin == rhs.hasIsAdmin) && (!lhs.hasIsAdmin || lhs.isAdmin == rhs.isAdmin)
  fieldCheck = fieldCheck && (lhs.hasIsActive == rhs.hasIsActive) && (!lhs.hasIsActive || lhs.isActive == rhs.isActive)
  fieldCheck = fieldCheck && (lhs.hasPhoneNumber == rhs.hasPhoneNumber) && (!lhs.hasPhoneNumber || lhs.phoneNumber == rhs.phoneNumber)
  fieldCheck = fieldCheck && (lhs.hasPhoneNumberVerified == rhs.hasPhoneNumberVerified) && (!lhs.hasPhoneNumberVerified || lhs.phoneNumberVerified == rhs.phoneNumberVerified)
  fieldCheck = fieldCheck && (lhs.hasPassword == rhs.hasPassword) && (!lhs.hasPassword || lhs.password == rhs.password)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal extension Services.User.Containers.User {
  internal struct UserRoot {
    internal static var sharedInstance : UserRoot {
     struct Static {
         static let instance : UserRoot = UserRoot()
     }
     return Static.instance
    }
    internal var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    internal func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final internal class UserV1 : GeneratedMessage, GeneratedMessageProtocol {
    private(set) var hasVersion:Bool = false
    private(set) var version:UInt32 = UInt32(1)

    private(set) var hasId:Bool = false
    private(set) var id:String = ""

    private(set) var hasPrimaryEmail:Bool = false
    private(set) var primaryEmail:String = ""

    private(set) var hasIsAdmin:Bool = false
    private(set) var isAdmin:Bool = false

    private(set) var hasIsActive:Bool = false
    private(set) var isActive:Bool = false

    private(set) var hasPhoneNumber:Bool = false
    private(set) var phoneNumber:String = ""

    private(set) var hasPhoneNumberVerified:Bool = false
    private(set) var phoneNumberVerified:Bool = false

    private(set) var hasPassword:Bool = false
    private(set) var password:String = ""

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasVersion {
        output.writeUInt32(1, value:version)
      }
      if hasId {
        output.writeString(2, value:id)
      }
      if hasPrimaryEmail {
        output.writeString(3, value:primaryEmail)
      }
      if hasIsAdmin {
        output.writeBool(4, value:isAdmin)
      }
      if hasIsActive {
        output.writeBool(5, value:isActive)
      }
      if hasPhoneNumber {
        output.writeString(6, value:phoneNumber)
      }
      if hasPhoneNumberVerified {
        output.writeBool(7, value:phoneNumberVerified)
      }
      if hasPassword {
        output.writeString(8, value:password)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasVersion {
        serialize_size += version.computeUInt32Size(1)
      }
      if hasId {
        serialize_size += id.computeStringSize(2)
      }
      if hasPrimaryEmail {
        serialize_size += primaryEmail.computeStringSize(3)
      }
      if hasIsAdmin {
        serialize_size += isAdmin.computeBoolSize(4)
      }
      if hasIsActive {
        serialize_size += isActive.computeBoolSize(5)
      }
      if hasPhoneNumber {
        serialize_size += phoneNumber.computeStringSize(6)
      }
      if hasPhoneNumberVerified {
        serialize_size += phoneNumberVerified.computeBoolSize(7)
      }
      if hasPassword {
        serialize_size += password.computeStringSize(8)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Services.User.Containers.User.UserV1 {
      return Services.User.Containers.User.UserV1.builder().mergeFromData(data, extensionRegistry:Services.User.Containers.User.UserRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Services.User.Containers.User.UserV1 {
      return Services.User.Containers.User.UserV1.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Services.User.Containers.User.UserV1 {
      return Services.User.Containers.User.UserV1.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) ->Services.User.Containers.User.UserV1 {
      return Services.User.Containers.User.UserV1.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Services.User.Containers.User.UserV1 {
      return Services.User.Containers.User.UserV1.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Services.User.Containers.User.UserV1 {
      return Services.User.Containers.User.UserV1.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Services.User.Containers.User.UserV1Builder {
      return Services.User.Containers.User.UserV1.classBuilder() as! Services.User.Containers.User.UserV1Builder
    }
    internal func builder() -> Services.User.Containers.User.UserV1Builder {
      return classBuilder() as! Services.User.Containers.User.UserV1Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Services.User.Containers.User.UserV1Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Services.User.Containers.User.UserV1.builder()
    }
    internal func toBuilder() -> Services.User.Containers.User.UserV1Builder {
      return Services.User.Containers.User.UserV1.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Services.User.Containers.User.UserV1) -> Services.User.Containers.User.UserV1Builder {
      return Services.User.Containers.User.UserV1.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasVersion {
        output += "\(indent) version: \(version) \n"
      }
      if hasId {
        output += "\(indent) id: \(id) \n"
      }
      if hasPrimaryEmail {
        output += "\(indent) primaryEmail: \(primaryEmail) \n"
      }
      if hasIsAdmin {
        output += "\(indent) isAdmin: \(isAdmin) \n"
      }
      if hasIsActive {
        output += "\(indent) isActive: \(isActive) \n"
      }
      if hasPhoneNumber {
        output += "\(indent) phoneNumber: \(phoneNumber) \n"
      }
      if hasPhoneNumberVerified {
        output += "\(indent) phoneNumberVerified: \(phoneNumberVerified) \n"
      }
      if hasPassword {
        output += "\(indent) password: \(password) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasVersion {
               hashCode = (hashCode &* 31) &+ version.hashValue
            }
            if hasId {
               hashCode = (hashCode &* 31) &+ id.hashValue
            }
            if hasPrimaryEmail {
               hashCode = (hashCode &* 31) &+ primaryEmail.hashValue
            }
            if hasIsAdmin {
               hashCode = (hashCode &* 31) &+ isAdmin.hashValue
            }
            if hasIsActive {
               hashCode = (hashCode &* 31) &+ isActive.hashValue
            }
            if hasPhoneNumber {
               hashCode = (hashCode &* 31) &+ phoneNumber.hashValue
            }
            if hasPhoneNumberVerified {
               hashCode = (hashCode &* 31) &+ phoneNumberVerified.hashValue
            }
            if hasPassword {
               hashCode = (hashCode &* 31) &+ password.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Services.User.Containers.User.UserV1"
    }
    override internal func className() -> String {
        return "Services.User.Containers.User.UserV1"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Services.User.Containers.User.UserV1.self
    }
    //Meta information declaration end

  }

  final internal class UserV1Builder : GeneratedMessageBuilder {
    private var builderResult:Services.User.Containers.User.UserV1

    required override internal init () {
       builderResult = Services.User.Containers.User.UserV1()
       super.init()
    }
    var hasVersion:Bool {
         get {
              return builderResult.hasVersion
         }
    }
    var version:UInt32 {
         get {
              return builderResult.version
         }
         set (value) {
             builderResult.hasVersion = true
             builderResult.version = value
         }
    }
    func setVersion(value:UInt32)-> Services.User.Containers.User.UserV1Builder {
      self.version = value
      return self
    }
    internal func clearVersion() -> Services.User.Containers.User.UserV1Builder{
         builderResult.hasVersion = false
         builderResult.version = UInt32(1)
         return self
    }
    var hasId:Bool {
         get {
              return builderResult.hasId
         }
    }
    var id:String {
         get {
              return builderResult.id
         }
         set (value) {
             builderResult.hasId = true
             builderResult.id = value
         }
    }
    func setId(value:String)-> Services.User.Containers.User.UserV1Builder {
      self.id = value
      return self
    }
    internal func clearId() -> Services.User.Containers.User.UserV1Builder{
         builderResult.hasId = false
         builderResult.id = ""
         return self
    }
    var hasPrimaryEmail:Bool {
         get {
              return builderResult.hasPrimaryEmail
         }
    }
    var primaryEmail:String {
         get {
              return builderResult.primaryEmail
         }
         set (value) {
             builderResult.hasPrimaryEmail = true
             builderResult.primaryEmail = value
         }
    }
    func setPrimaryEmail(value:String)-> Services.User.Containers.User.UserV1Builder {
      self.primaryEmail = value
      return self
    }
    internal func clearPrimaryEmail() -> Services.User.Containers.User.UserV1Builder{
         builderResult.hasPrimaryEmail = false
         builderResult.primaryEmail = ""
         return self
    }
    var hasIsAdmin:Bool {
         get {
              return builderResult.hasIsAdmin
         }
    }
    var isAdmin:Bool {
         get {
              return builderResult.isAdmin
         }
         set (value) {
             builderResult.hasIsAdmin = true
             builderResult.isAdmin = value
         }
    }
    func setIsAdmin(value:Bool)-> Services.User.Containers.User.UserV1Builder {
      self.isAdmin = value
      return self
    }
    internal func clearIsAdmin() -> Services.User.Containers.User.UserV1Builder{
         builderResult.hasIsAdmin = false
         builderResult.isAdmin = false
         return self
    }
    var hasIsActive:Bool {
         get {
              return builderResult.hasIsActive
         }
    }
    var isActive:Bool {
         get {
              return builderResult.isActive
         }
         set (value) {
             builderResult.hasIsActive = true
             builderResult.isActive = value
         }
    }
    func setIsActive(value:Bool)-> Services.User.Containers.User.UserV1Builder {
      self.isActive = value
      return self
    }
    internal func clearIsActive() -> Services.User.Containers.User.UserV1Builder{
         builderResult.hasIsActive = false
         builderResult.isActive = false
         return self
    }
    var hasPhoneNumber:Bool {
         get {
              return builderResult.hasPhoneNumber
         }
    }
    var phoneNumber:String {
         get {
              return builderResult.phoneNumber
         }
         set (value) {
             builderResult.hasPhoneNumber = true
             builderResult.phoneNumber = value
         }
    }
    func setPhoneNumber(value:String)-> Services.User.Containers.User.UserV1Builder {
      self.phoneNumber = value
      return self
    }
    internal func clearPhoneNumber() -> Services.User.Containers.User.UserV1Builder{
         builderResult.hasPhoneNumber = false
         builderResult.phoneNumber = ""
         return self
    }
    var hasPhoneNumberVerified:Bool {
         get {
              return builderResult.hasPhoneNumberVerified
         }
    }
    var phoneNumberVerified:Bool {
         get {
              return builderResult.phoneNumberVerified
         }
         set (value) {
             builderResult.hasPhoneNumberVerified = true
             builderResult.phoneNumberVerified = value
         }
    }
    func setPhoneNumberVerified(value:Bool)-> Services.User.Containers.User.UserV1Builder {
      self.phoneNumberVerified = value
      return self
    }
    internal func clearPhoneNumberVerified() -> Services.User.Containers.User.UserV1Builder{
         builderResult.hasPhoneNumberVerified = false
         builderResult.phoneNumberVerified = false
         return self
    }
    var hasPassword:Bool {
         get {
              return builderResult.hasPassword
         }
    }
    var password:String {
         get {
              return builderResult.password
         }
         set (value) {
             builderResult.hasPassword = true
             builderResult.password = value
         }
    }
    func setPassword(value:String)-> Services.User.Containers.User.UserV1Builder {
      self.password = value
      return self
    }
    internal func clearPassword() -> Services.User.Containers.User.UserV1Builder{
         builderResult.hasPassword = false
         builderResult.password = ""
         return self
    }
    override internal var internalGetResult:GeneratedMessage {
         get {
            return builderResult
         }
    }
    internal override func clear() -> Services.User.Containers.User.UserV1Builder {
      builderResult = Services.User.Containers.User.UserV1()
      return self
    }
    internal override func clone() -> Services.User.Containers.User.UserV1Builder {
      return Services.User.Containers.User.UserV1.builderWithPrototype(builderResult)
    }
    internal override func build() -> Services.User.Containers.User.UserV1 {
         checkInitialized()
         return buildPartial()
    }
    internal func buildPartial() -> Services.User.Containers.User.UserV1 {
      var returnMe:Services.User.Containers.User.UserV1 = builderResult
      return returnMe
    }
    internal func mergeFrom(other:Services.User.Containers.User.UserV1) -> Services.User.Containers.User.UserV1Builder {
      if (other == Services.User.Containers.User.UserV1()) {
       return self
      }
      if other.hasVersion {
           version = other.version
      }
      if other.hasId {
           id = other.id
      }
      if other.hasPrimaryEmail {
           primaryEmail = other.primaryEmail
      }
      if other.hasIsAdmin {
           isAdmin = other.isAdmin
      }
      if other.hasIsActive {
           isActive = other.isActive
      }
      if other.hasPhoneNumber {
           phoneNumber = other.phoneNumber
      }
      if other.hasPhoneNumberVerified {
           phoneNumberVerified = other.phoneNumberVerified
      }
      if other.hasPassword {
           password = other.password
      }
      mergeUnknownFields(other.unknownFields)
      return self
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream) ->Services.User.Containers.User.UserV1Builder {
         return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Services.User.Containers.User.UserV1Builder {
      var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
      while (true) {
        var tag = input.readTag()
        switch tag {
        case 0: 
          self.unknownFields = unknownFieldsBuilder.build()
          return self

        case 8 :
          version = input.readUInt32()

        case 18 :
          id = input.readString()

        case 26 :
          primaryEmail = input.readString()

        case 32 :
          isAdmin = input.readBool()

        case 40 :
          isActive = input.readBool()

        case 50 :
          phoneNumber = input.readString()

        case 56 :
          phoneNumberVerified = input.readBool()

        case 66 :
          password = input.readString()

        default:
          if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
             unknownFields = unknownFieldsBuilder.build()
             return self
          }
        }
      }
    }
  }

}

// @@protoc_insertion_point(global_scope)
