// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source file who_can_view_membership.proto

import Foundation

public extension Services.Group.Containers.Permissions{ public struct WhoCanViewMembership { }}

public extension Services.Group.Containers.Permissions.WhoCanViewMembership {
  public struct WhoCanViewMembershipRoot {
    public static var sharedInstance : WhoCanViewMembershipRoot {
     struct Static {
         static let instance : WhoCanViewMembershipRoot = WhoCanViewMembershipRoot()
     }
     return Static.instance
    }
    public var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    public func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }



  //Enum type declaration start 

  public enum WhoCanViewMembershipPermissionsV1:Int32 {
    case AllInDomain = 0
    case AllMembers = 1
    case AllManagers = 2

  }

  //Enum type declaration end 

}

// @@protoc_insertion_point(global_scope)
