// Generated by the protocol buffer compiler.  DO NOT EDIT!

import Foundation
import ProtocolBuffers


internal extension Services.Media{ internal struct Containers { internal struct Instructions { }}}

internal func == (lhs: Services.Media.Containers.Instructions.UploadInstructionsV1, rhs: Services.Media.Containers.Instructions.UploadInstructionsV1) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasVersion == rhs.hasVersion) && (!lhs.hasVersion || lhs.version == rhs.version)
  fieldCheck = fieldCheck && (lhs.hasUploadId == rhs.hasUploadId) && (!lhs.hasUploadId || lhs.uploadId == rhs.uploadId)
  fieldCheck = fieldCheck && (lhs.hasUploadUrl == rhs.hasUploadUrl) && (!lhs.hasUploadUrl || lhs.uploadUrl == rhs.uploadUrl)
  fieldCheck = fieldCheck && (lhs.hasUploadKey == rhs.hasUploadKey) && (!lhs.hasUploadKey || lhs.uploadKey == rhs.uploadKey)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal extension Services.Media.Containers.Instructions {
  internal struct InstructionsRoot {
    internal static var sharedInstance : InstructionsRoot {
     struct Static {
         static let instance : InstructionsRoot = InstructionsRoot()
     }
     return Static.instance
    }
    internal var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    internal func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final internal class UploadInstructionsV1 : GeneratedMessage, GeneratedMessageProtocol {
    private(set) var hasVersion:Bool = false
    private(set) var version:UInt32 = UInt32(1)

    private(set) var hasUploadId:Bool = false
    private(set) var uploadId:String = ""

    private(set) var hasUploadUrl:Bool = false
    private(set) var uploadUrl:String = ""

    private(set) var hasUploadKey:Bool = false
    private(set) var uploadKey:String = ""

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasVersion {
        output.writeUInt32(1, value:version)
      }
      if hasUploadId {
        output.writeString(2, value:uploadId)
      }
      if hasUploadUrl {
        output.writeString(3, value:uploadUrl)
      }
      if hasUploadKey {
        output.writeString(4, value:uploadKey)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasVersion {
        serialize_size += version.computeUInt32Size(1)
      }
      if hasUploadId {
        serialize_size += uploadId.computeStringSize(2)
      }
      if hasUploadUrl {
        serialize_size += uploadUrl.computeStringSize(3)
      }
      if hasUploadKey {
        serialize_size += uploadKey.computeStringSize(4)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Services.Media.Containers.Instructions.UploadInstructionsV1 {
      return Services.Media.Containers.Instructions.UploadInstructionsV1.builder().mergeFromData(data, extensionRegistry:Services.Media.Containers.Instructions.InstructionsRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Services.Media.Containers.Instructions.UploadInstructionsV1 {
      return Services.Media.Containers.Instructions.UploadInstructionsV1.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Services.Media.Containers.Instructions.UploadInstructionsV1 {
      return Services.Media.Containers.Instructions.UploadInstructionsV1.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) ->Services.Media.Containers.Instructions.UploadInstructionsV1 {
      return Services.Media.Containers.Instructions.UploadInstructionsV1.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Services.Media.Containers.Instructions.UploadInstructionsV1 {
      return Services.Media.Containers.Instructions.UploadInstructionsV1.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Services.Media.Containers.Instructions.UploadInstructionsV1 {
      return Services.Media.Containers.Instructions.UploadInstructionsV1.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
      return Services.Media.Containers.Instructions.UploadInstructionsV1.classBuilder() as! Services.Media.Containers.Instructions.UploadInstructionsV1Builder
    }
    internal func builder() -> Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
      return classBuilder() as! Services.Media.Containers.Instructions.UploadInstructionsV1Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Services.Media.Containers.Instructions.UploadInstructionsV1Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Services.Media.Containers.Instructions.UploadInstructionsV1.builder()
    }
    internal func toBuilder() -> Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
      return Services.Media.Containers.Instructions.UploadInstructionsV1.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Services.Media.Containers.Instructions.UploadInstructionsV1) -> Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
      return Services.Media.Containers.Instructions.UploadInstructionsV1.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasVersion {
        output += "\(indent) version: \(version) \n"
      }
      if hasUploadId {
        output += "\(indent) uploadId: \(uploadId) \n"
      }
      if hasUploadUrl {
        output += "\(indent) uploadUrl: \(uploadUrl) \n"
      }
      if hasUploadKey {
        output += "\(indent) uploadKey: \(uploadKey) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasVersion {
               hashCode = (hashCode &* 31) &+ version.hashValue
            }
            if hasUploadId {
               hashCode = (hashCode &* 31) &+ uploadId.hashValue
            }
            if hasUploadUrl {
               hashCode = (hashCode &* 31) &+ uploadUrl.hashValue
            }
            if hasUploadKey {
               hashCode = (hashCode &* 31) &+ uploadKey.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Services.Media.Containers.Instructions.UploadInstructionsV1"
    }
    override internal func className() -> String {
        return "Services.Media.Containers.Instructions.UploadInstructionsV1"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Services.Media.Containers.Instructions.UploadInstructionsV1.self
    }
    //Meta information declaration end

  }

  final internal class UploadInstructionsV1Builder : GeneratedMessageBuilder {
    private var builderResult:Services.Media.Containers.Instructions.UploadInstructionsV1

    required override internal init () {
       builderResult = Services.Media.Containers.Instructions.UploadInstructionsV1()
       super.init()
    }
    var hasVersion:Bool {
         get {
              return builderResult.hasVersion
         }
    }
    var version:UInt32 {
         get {
              return builderResult.version
         }
         set (value) {
             builderResult.hasVersion = true
             builderResult.version = value
         }
    }
    func setVersion(value:UInt32)-> Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
      self.version = value
      return self
    }
    internal func clearVersion() -> Services.Media.Containers.Instructions.UploadInstructionsV1Builder{
         builderResult.hasVersion = false
         builderResult.version = UInt32(1)
         return self
    }
    var hasUploadId:Bool {
         get {
              return builderResult.hasUploadId
         }
    }
    var uploadId:String {
         get {
              return builderResult.uploadId
         }
         set (value) {
             builderResult.hasUploadId = true
             builderResult.uploadId = value
         }
    }
    func setUploadId(value:String)-> Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
      self.uploadId = value
      return self
    }
    internal func clearUploadId() -> Services.Media.Containers.Instructions.UploadInstructionsV1Builder{
         builderResult.hasUploadId = false
         builderResult.uploadId = ""
         return self
    }
    var hasUploadUrl:Bool {
         get {
              return builderResult.hasUploadUrl
         }
    }
    var uploadUrl:String {
         get {
              return builderResult.uploadUrl
         }
         set (value) {
             builderResult.hasUploadUrl = true
             builderResult.uploadUrl = value
         }
    }
    func setUploadUrl(value:String)-> Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
      self.uploadUrl = value
      return self
    }
    internal func clearUploadUrl() -> Services.Media.Containers.Instructions.UploadInstructionsV1Builder{
         builderResult.hasUploadUrl = false
         builderResult.uploadUrl = ""
         return self
    }
    var hasUploadKey:Bool {
         get {
              return builderResult.hasUploadKey
         }
    }
    var uploadKey:String {
         get {
              return builderResult.uploadKey
         }
         set (value) {
             builderResult.hasUploadKey = true
             builderResult.uploadKey = value
         }
    }
    func setUploadKey(value:String)-> Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
      self.uploadKey = value
      return self
    }
    internal func clearUploadKey() -> Services.Media.Containers.Instructions.UploadInstructionsV1Builder{
         builderResult.hasUploadKey = false
         builderResult.uploadKey = ""
         return self
    }
    override internal var internalGetResult:GeneratedMessage {
         get {
            return builderResult
         }
    }
    internal override func clear() -> Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
      builderResult = Services.Media.Containers.Instructions.UploadInstructionsV1()
      return self
    }
    internal override func clone() -> Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
      return Services.Media.Containers.Instructions.UploadInstructionsV1.builderWithPrototype(builderResult)
    }
    internal override func build() -> Services.Media.Containers.Instructions.UploadInstructionsV1 {
         checkInitialized()
         return buildPartial()
    }
    internal func buildPartial() -> Services.Media.Containers.Instructions.UploadInstructionsV1 {
      var returnMe:Services.Media.Containers.Instructions.UploadInstructionsV1 = builderResult
      return returnMe
    }
    internal func mergeFrom(other:Services.Media.Containers.Instructions.UploadInstructionsV1) -> Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
      if (other == Services.Media.Containers.Instructions.UploadInstructionsV1()) {
       return self
      }
      if other.hasVersion {
           version = other.version
      }
      if other.hasUploadId {
           uploadId = other.uploadId
      }
      if other.hasUploadUrl {
           uploadUrl = other.uploadUrl
      }
      if other.hasUploadKey {
           uploadKey = other.uploadKey
      }
      mergeUnknownFields(other.unknownFields)
      return self
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream) ->Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
         return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Services.Media.Containers.Instructions.UploadInstructionsV1Builder {
      var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
      while (true) {
        var tag = input.readTag()
        switch tag {
        case 0: 
          self.unknownFields = unknownFieldsBuilder.build()
          return self

        case 8 :
          version = input.readUInt32()

        case 18 :
          uploadId = input.readString()

        case 26 :
          uploadUrl = input.readString()

        case 34 :
          uploadKey = input.readString()

        default:
          if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
             unknownFields = unknownFieldsBuilder.build()
             return self
          }
        }
      }
    }
  }

}

// @@protoc_insertion_point(global_scope)
