# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/performance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import google.protobuf.swift_descriptor_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/protobuf/performance.proto',
  package='',
  serialized_pb=_b('\n!google/protobuf/performance.proto\x1a&google/protobuf/swift-descriptor.proto\"\x1d\n\x04User\x12\x15\n\x05group\x18\x01 \x01(\x0b\x32\x06.Group\"\x1d\n\x05Group\x12\x14\n\x05owner\x18\x01 \x01(\x0b\x32\x05.User\"-\n\x0fPerfomanceBatch\x12\x1a\n\x05\x62\x61tch\x18\x01 \x03(\x0b\x32\x0b.Perfomance\"|\n\nPerfomance\x12\x0c\n\x04ints\x18\x01 \x02(\x05\x12\x0e\n\x06ints64\x18\x02 \x02(\x03\x12\x0f\n\x07\x64oubles\x18\x03 \x02(\x01\x12\x0e\n\x06\x66loats\x18\x04 \x02(\x02\x12\x0b\n\x03str\x18\x05 \x01(\t\x12\r\n\x05\x62ytes\x18\x06 \x01(\x0c\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\tB\x07\xf2\xaa\xb6\x13\x02\x10\x01')
  ,
  dependencies=[google.protobuf.swift_descriptor_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='User.group', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=106,
)


_GROUP = _descriptor.Descriptor(
  name='Group',
  full_name='Group',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='Group.owner', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=137,
)


_PERFOMANCEBATCH = _descriptor.Descriptor(
  name='PerfomanceBatch',
  full_name='PerfomanceBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batch', full_name='PerfomanceBatch.batch', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=184,
)


_PERFOMANCE = _descriptor.Descriptor(
  name='Perfomance',
  full_name='Perfomance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ints', full_name='Perfomance.ints', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ints64', full_name='Perfomance.ints64', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doubles', full_name='Perfomance.doubles', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floats', full_name='Perfomance.floats', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str', full_name='Perfomance.str', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='Perfomance.bytes', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='Perfomance.description', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=310,
)

_USER.fields_by_name['group'].message_type = _GROUP
_GROUP.fields_by_name['owner'].message_type = _USER
_PERFOMANCEBATCH.fields_by_name['batch'].message_type = _PERFOMANCE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Group'] = _GROUP
DESCRIPTOR.message_types_by_name['PerfomanceBatch'] = _PERFOMANCEBATCH
DESCRIPTOR.message_types_by_name['Perfomance'] = _PERFOMANCE

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'google.protobuf.performance_pb2'
  # @@protoc_insertion_point(class_scope:User)
  ))
_sym_db.RegisterMessage(User)

Group = _reflection.GeneratedProtocolMessageType('Group', (_message.Message,), dict(
  DESCRIPTOR = _GROUP,
  __module__ = 'google.protobuf.performance_pb2'
  # @@protoc_insertion_point(class_scope:Group)
  ))
_sym_db.RegisterMessage(Group)

PerfomanceBatch = _reflection.GeneratedProtocolMessageType('PerfomanceBatch', (_message.Message,), dict(
  DESCRIPTOR = _PERFOMANCEBATCH,
  __module__ = 'google.protobuf.performance_pb2'
  # @@protoc_insertion_point(class_scope:PerfomanceBatch)
  ))
_sym_db.RegisterMessage(PerfomanceBatch)

Perfomance = _reflection.GeneratedProtocolMessageType('Perfomance', (_message.Message,), dict(
  DESCRIPTOR = _PERFOMANCE,
  __module__ = 'google.protobuf.performance_pb2'
  # @@protoc_insertion_point(class_scope:Perfomance)
  ))
_sym_db.RegisterMessage(Perfomance)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\362\252\266\023\002\020\001'))
# @@protoc_insertion_point(module_scope)
