// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./src/protobufs/services/profile/actions/get_attributes_for_profiles.proto
package com.rhlabs.protobufs.services.profile.actions.get_attributes_for_profiles;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Label.REPEATED;

public final class GetAttributesForProfilesRequestV1 extends Message {
  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_VERSION = 1;
  public static final List<String> DEFAULT_ATTRIBUTES = Collections.emptyList();
  public static final Boolean DEFAULT_DISTINCT = false;
  public static final String DEFAULT_LOCATION_ID = "";

  @ProtoField(tag = 1, type = UINT32)
  public final Integer version;

  @ProtoField(tag = 2, type = STRING, label = REPEATED)
  public final List<String> attributes;

  @ProtoField(tag = 3, type = BOOL)
  public final Boolean distinct;

  @ProtoField(tag = 4, type = STRING)
  public final String location_id;

  public GetAttributesForProfilesRequestV1(Integer version, List<String> attributes, Boolean distinct, String location_id) {
    this.version = version;
    this.attributes = immutableCopyOf(attributes);
    this.distinct = distinct;
    this.location_id = location_id;
  }

  private GetAttributesForProfilesRequestV1(Builder builder) {
    this(builder.version, builder.attributes, builder.distinct, builder.location_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetAttributesForProfilesRequestV1)) return false;
    GetAttributesForProfilesRequestV1 o = (GetAttributesForProfilesRequestV1) other;
    return equals(version, o.version)
        && equals(attributes, o.attributes)
        && equals(distinct, o.distinct)
        && equals(location_id, o.location_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = version != null ? version.hashCode() : 0;
      result = result * 37 + (attributes != null ? attributes.hashCode() : 1);
      result = result * 37 + (distinct != null ? distinct.hashCode() : 0);
      result = result * 37 + (location_id != null ? location_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<GetAttributesForProfilesRequestV1> {

    public Integer version;
    public List<String> attributes;
    public Boolean distinct;
    public String location_id;

    public Builder() {
    }

    public Builder(GetAttributesForProfilesRequestV1 message) {
      super(message);
      if (message == null) return;
      this.version = message.version;
      this.attributes = copyOf(message.attributes);
      this.distinct = message.distinct;
      this.location_id = message.location_id;
    }

    public Builder version(Integer version) {
      this.version = version;
      return this;
    }

    public Builder attributes(List<String> attributes) {
      this.attributes = checkForNulls(attributes);
      return this;
    }

    public Builder distinct(Boolean distinct) {
      this.distinct = distinct;
      return this;
    }

    public Builder location_id(String location_id) {
      this.location_id = location_id;
      return this;
    }

    @Override
    public GetAttributesForProfilesRequestV1 build() {
      return new GetAttributesForProfilesRequestV1(this);
    }
  }
}
